Add support for passing a path with different swagger files
Hacker0x01/widdershins pull request #13
Opened 2021-06-25 16:03 UTC by chriszo111

2021-06-25 16:04 UTC, chriszo111 commented
Wait with merge until `core` is ready

2021-06-29 09:08 UTC, saida requested changes

2021-06-29 09:08 UTC, saida commented on templates/openapi3/reference.dot
> +{{ } }}
I think we can remove this file now.

2021-06-29 09:12 UTC, chriszo111 commented on templates/openapi3/reference.dot
> +{{ } }}
Woops, I thought I did. Updated!

2021-06-29 09:13 UTC, merged

2021-06-29 09:13 UTC, saida approved these changes